#!/bin/bash
#SBATCH -N 2 # request 1 nodes
##SBATCH --nodelist=node01,node02
#SBATCH --output=netgauge_run_%j.stdout    # standard output will be redirected to this file, where the % is replaced with the job allocation number.
#SBATCH -J "netgauge_run"    # this is your job’s name
#SBATCH --gpus-per-node=1

# ---[ Script Setup ]---

set -e

# module load mpich

export LD_LIBRARY_PATH=/home/liuyao/software/mpich_4_1_1_pgcc/lib:$LD_LIBRARY_PATH
export PATH=/home/liuyao/software/mpich_4_1_1_pgcc/bin:$PATH
export C_INCLUDE_PATH=/home/liuyao/software/mpich_4_1_1_pgcc/include:$C_INCLUDE_PATH

MPI_HOME="/home/liuyao/software/mpich_4_1_1_pgcc"
export MPI_HOME

source /home/liuyao/sbatch_sh/.nvccrc

export NCCL_HOME=/home/liuyao/NCCL/deps-nccl/nccl/build
export LD_LIBRARY_PATH="${NCCL_HOME}/lib:$LD_LIBRARY_PATH"
export PATH="${NCCL_HOME}/include:$PATH"



# echo $MALLOC_CHECK_

# for the shared library generated by myself

export LD_LIBRARY_PATH=/home/liuyao/software/Netgauge/libnccl:$LD_LIBRARY_PATH

ldd /home/liuyao/software/Netgauge/libnccl/libMyNcclCode.so

# export MALLOC_CHECK_=2
# echo $MALLOC_CHECK_

echo "mpirun -n 2 /home/liuyao/software/Netgauge/netgauge -m mpi -x loggp -o ng_logGP_internode"

dool --time --mem --cpu --net -N ib0,ens786f1,lo,total 1 > /home/liuyao/sbatch_sh/netgauge/run/output/CPU.csv  &
        nvidia-smi --query-gpu=name,timestamp,uuid,utilization.gpu,memory.total,utilization.memory,power.draw --format=csv -l 1 > /home/liuyao/sbatch_sh/netgauge/run/output/GPU.csv &
        sh rtop.sh -d ib0 > /home/liuyao/sbatch_sh/netgauge/run/output/RTOP.csv  &

# mpirun -n 2 /home/ldai8/software/netgauge-2.4.6/netgauge --verbosity 3 -t 30 -s 1048576 -c 20 -g 65535 -x loggp -o

UCX_NET_DEVICES=mlx5_0:1 mpirun -n 2  /home/liuyao/software/Netgauge_default/netgauge -h

UCX_NET_DEVICES=mlx5_0:1 mpirun -n 2 -ppn 1 /home/liuyao/software/Netgauge/netgauge -m mpi -x loggp -o ng_logGP_internode -s 1-131072

# mpiexec -n 2 -ppn 1 gdb --args /home/ldai8/software/Netgauge/netgauge -m mpi -x loggp -o ng_logGP_internode : -n 2 -ppn 1 \
#  /home/ldai8/software/Netgauge/netgauge -m mpi -x loggp -o ng_logGP_internode



